services:
  server:
    build:
      context: .
      dockerfile: infra/server.Dockerfile
    environment:
      TEAMOTP_DB_PATH: "/app/data/teamotp.test.db"
    volumes:
      - ./server/data:/app/data
      - ./server/config.toml:/app/config.toml
    ports:
      - "3000:3000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: infra/client.Dockerfile
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
